version: '3'

services:
  app:
    build: .
    container_name: dashboard
    ports:
      - "9023:9023"  # Mapeia a porta 9023 do container para a mesma porta no host
    volumes:
      - .:/app  # Monta o diretório atual (opcional, apenas se precisar de desenvolvimento)
    network_mode: "host"  # Usa o modo de rede host para permitir acesso externo
    stdin_open: true
    tty: true
    command: http-server dist -p 9023 -a 0.0.0.0
